# Generated by Django 2.2 on 2020-03-14 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='Файл')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('access', models.CharField(choices=[('base', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='base', max_length=20, verbose_name='Доступ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
