# Generated by Django 2.2 on 2020-03-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200314_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privates', to='webapp.File'),
        ),
        migrations.AlterField(
            model_name='private',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
